Repository TeamProject-Farmer/back-end, pull requests merged in 2023-07, with the labels that each got.

#75 Feature/user/join login : 로그인 버그 수정
  src/main/java/com/farmer/backend/api/controller/banner/BannerController.java
  src/main/java/com/farmer/backend/api/controller/banner/response/ResponseBannerDtoList.java
  src/main/java/com/farmer/backend/api/controller/login/RequestOAuthUserInfoDto.java
  src/main/java/com/farmer/backend/api/controller/login/ResponseLoginMemberDto.java
  src/main/java/com/farmer/backend/api/controller/login/ResponseOAuthUserInfoDto.java
  src/main/java/com/farmer/backend/api/controller/member/MemberController.java
  src/main/java/com/farmer/backend/api/service/banner/BannerService.java
  src/main/java/com/farmer/backend/api/service/member/MemberService.java
  src/main/java/com/farmer/backend/config/SecurityConfig.java
  src/main/java/com/farmer/backend/domain/banner/Banner.java
  src/main/java/com/farmer/backend/domain/banner/BannerQueryRepository.java
  src/main/java/com/farmer/backend/domain/banner/BannerQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/domain/memberscoupon/MemberCouponRepository.java
  src/main/java/com/farmer/backend/domain/memberscoupon/MembersCoupon.java
  src/main/java/com/farmer/backend/login/general/handler/LoginSuccessHandler.java
  src/main/java/com/farmer/backend/login/oauth/userInfo/GoogleSocialLogin.java
  src/main/java/com/farmer/backend/login/oauth/userInfo/KakaoSocialLogin.java
  src/main/java/com/farmer/backend/login/oauth/userInfo/NaverSocialLogin.java
  src/main/java/com/farmer/backend/login/oauth/userInfo/OAuthLogin.java
  src/test/java/com/farmer/backend/api/service/banner/BannerServiceTest.java
Labels: bug, refactor, feature

#71 Feature/feature/user/banner : 배너 도메인 개발
  src/main/java/com/farmer/backend/api/controller/banner/BannerController.java
  src/main/java/com/farmer/backend/api/controller/banner/response/ResponseBannerDtoList.java
  src/main/java/com/farmer/backend/api/service/banner/BannerService.java
  src/main/java/com/farmer/backend/domain/banner/Banner.java
  src/main/java/com/farmer/backend/domain/banner/BannerQueryRepository.java
  src/main/java/com/farmer/backend/domain/banner/BannerQueryRepositoryImpl.java
  src/test/java/com/farmer/backend/api/service/banner/BannerServiceTest.java
Labels: feature

#81 Feature/user/member : 회원 마이페이지 프로필 수정, 쿠폰 조회
  src/main/java/com/farmer/backend/api/controller/coupon/CouponController.java
  src/main/java/com/farmer/backend/api/controller/coupon/response/ResponseMembersCouponDto.java
  src/main/java/com/farmer/backend/api/controller/join/JoinController.java
  src/main/java/com/farmer/backend/api/controller/login/ResponseLoginMemberDto.java
  src/main/java/com/farmer/backend/api/controller/member/MemberController.java
  src/main/java/com/farmer/backend/api/controller/member/request/RequestMemberProfileDto.java
  src/main/java/com/farmer/backend/api/service/member/MemberService.java
  src/main/java/com/farmer/backend/api/service/membersCoupon/membersCouponService.java
  src/main/java/com/farmer/backend/config/SecurityConfig.java
  src/main/java/com/farmer/backend/domain/coupon/Coupon.java
  src/main/java/com/farmer/backend/domain/member/Member.java
  src/main/java/com/farmer/backend/domain/memberscoupon/MemberCouponRepository.java
  src/main/java/com/farmer/backend/domain/memberscoupon/MembersCouponQueryRepository.java
  src/main/java/com/farmer/backend/domain/memberscoupon/MembersCouponQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/exception/ErrorCode.java
  src/main/java/com/farmer/backend/jwt/JwtAuthenticationProcessingFilter.java
  src/main/java/com/farmer/backend/jwt/JwtService.java
  src/main/java/com/farmer/backend/login/general/LoginService.java
  src/main/java/com/farmer/backend/login/general/MemberAdapter.java
  src/main/java/com/farmer/backend/login/general/handler/LoginSuccessHandler.java
  src/test/java/com/farmer/backend/api/service/member/MemberServiceTest.java
Labels: feature

#82 Feature/user/order-product: 주문 상품 리스트 날짜 포맷 변경
  src/main/java/com/farmer/backend/api/controller/news/NewsController.java
  src/main/java/com/farmer/backend/api/controller/news/response/ResponseNewsDto.java
  src/main/java/com/farmer/backend/api/controller/orderproduct/OrderProductController.java
  src/main/java/com/farmer/backend/api/controller/orderproduct/request/RequestOrderProductStatusSearchDto.java
  src/main/java/com/farmer/backend/api/controller/orderproduct/response/ResponseOrderProductDetailDto.java
  src/main/java/com/farmer/backend/api/controller/orderproduct/response/ResponseOrderProductDto.java
  src/main/java/com/farmer/backend/api/service/news/NewsService.java
  src/main/java/com/farmer/backend/api/service/orderproduct/OrderProductService.java
  src/main/java/com/farmer/backend/domain/news/News.java
  src/main/java/com/farmer/backend/domain/news/NewsExposure.java
  src/main/java/com/farmer/backend/domain/news/NewsRepository.java
  src/main/java/com/farmer/backend/domain/orderproduct/OrderProductQueryRepository.java
  src/main/java/com/farmer/backend/domain/orderproduct/OrderProductQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/domain/orderproduct/OrderProductRepository.java
  src/main/java/com/farmer/backend/domain/orders/OrderRepository.java
  src/main/java/com/farmer/backend/domain/orders/Orders.java
  src/main/java/com/farmer/backend/exception/ErrorCode.java
  src/main/java/com/farmer/backend/login/general/LoginService.java
  src/main/java/com/farmer/backend/login/general/MemberAdapter.java
  src/test/java/com/farmer/backend/api/controller/orderproduct/OrderProductControllerTest.java
  src/test/java/com/farmer/backend/api/service/news/NewsServiceTest.java
  src/test/java/com/farmer/backend/api/service/orderproduct/OrderProductServiceTest.java
  src/test/java/com/farmer/backend/api/service/product/ProductServiceTest.java
  src/test/java/com/farmer/backend/config/WithMockCustomUser.java
  src/test/java/com/farmer/backend/config/WithMockCustomUserSecurityContextFactory.java
Labels: bug, refactor

#83 Feature/user/order-product: 주문 상품 리스트 날짜 포맷 변경
  src/main/java/com/farmer/backend/api/controller/coupon/CouponController.java
  src/main/java/com/farmer/backend/api/controller/coupon/response/ResponseMembersCouponDto.java
  src/main/java/com/farmer/backend/api/controller/join/JoinController.java
  src/main/java/com/farmer/backend/api/controller/login/ResponseLoginMemberDto.java
  src/main/java/com/farmer/backend/api/controller/member/MemberController.java
  src/main/java/com/farmer/backend/api/controller/member/request/RequestMemberProfileDto.java
  src/main/java/com/farmer/backend/api/controller/news/NewsController.java
  src/main/java/com/farmer/backend/api/controller/news/response/ResponseNewsDto.java
  src/main/java/com/farmer/backend/api/controller/orderproduct/OrderProductController.java
  src/main/java/com/farmer/backend/api/controller/orderproduct/request/RequestOrderProductStatusSearchDto.java
  src/main/java/com/farmer/backend/api/controller/orderproduct/response/ResponseOrderProductDetailDto.java
  src/main/java/com/farmer/backend/api/controller/orderproduct/response/ResponseOrderProductDto.java
  src/main/java/com/farmer/backend/api/service/member/MemberService.java
  src/main/java/com/farmer/backend/api/service/membersCoupon/membersCouponService.java
  src/main/java/com/farmer/backend/api/service/news/NewsService.java
  src/main/java/com/farmer/backend/api/service/orderproduct/OrderProductService.java
  src/main/java/com/farmer/backend/config/SecurityConfig.java
  src/main/java/com/farmer/backend/domain/coupon/Coupon.java
  src/main/java/com/farmer/backend/domain/member/Member.java
  src/main/java/com/farmer/backend/domain/memberscoupon/MemberCouponRepository.java
  src/main/java/com/farmer/backend/domain/memberscoupon/MembersCouponQueryRepository.java
  src/main/java/com/farmer/backend/domain/memberscoupon/MembersCouponQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/domain/news/News.java
  src/main/java/com/farmer/backend/domain/news/NewsExposure.java
  src/main/java/com/farmer/backend/domain/news/NewsRepository.java
  src/main/java/com/farmer/backend/domain/orderproduct/OrderProductQueryRepository.java
  src/main/java/com/farmer/backend/domain/orderproduct/OrderProductQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/domain/orderproduct/OrderProductRepository.java
  src/main/java/com/farmer/backend/domain/orders/OrderRepository.java
  src/main/java/com/farmer/backend/domain/orders/Orders.java
  src/main/java/com/farmer/backend/exception/ErrorCode.java
  src/main/java/com/farmer/backend/jwt/JwtAuthenticationProcessingFilter.java
  src/main/java/com/farmer/backend/jwt/JwtService.java
  src/main/java/com/farmer/backend/login/general/LoginService.java
  src/main/java/com/farmer/backend/login/general/MemberAdapter.java
  src/main/java/com/farmer/backend/login/general/handler/LoginSuccessHandler.java
  src/test/java/com/farmer/backend/api/controller/orderproduct/OrderProductControllerTest.java
  src/test/java/com/farmer/backend/api/service/member/MemberServiceTest.java
  src/test/java/com/farmer/backend/api/service/news/NewsServiceTest.java
  src/test/java/com/farmer/backend/api/service/orderproduct/OrderProductServiceTest.java
  src/test/java/com/farmer/backend/api/service/product/ProductServiceTest.java
  src/test/java/com/farmer/backend/config/WithMockCustomUser.java
  src/test/java/com/farmer/backend/config/WithMockCustomUserSecurityContextFactory.java
Labels: bug, test, refactor, feature

#91 Feature/user/review : 리뷰 도메인 기능 개발
  src/main/java/com/farmer/backend/api/controller/review/ReviewController.java
  src/main/java/com/farmer/backend/api/controller/review/request/RequestReviewStarDto.java
  src/main/java/com/farmer/backend/api/controller/review/request/SearchProductReviewCondition.java
  src/main/java/com/farmer/backend/api/controller/review/response/ResponseBestReviewListDto.java
  src/main/java/com/farmer/backend/api/controller/review/response/ResponseProductReviewListDto.java
  src/main/java/com/farmer/backend/api/controller/review/response/ResponseReviewStarDto.java
  src/main/java/com/farmer/backend/api/service/review/ReviewService.java
  src/main/java/com/farmer/backend/domain/product/ProductRepository.java
  src/main/java/com/farmer/backend/domain/product/productreview/ProductReviewQueryRepository.java
  src/main/java/com/farmer/backend/domain/product/productreview/ProductReviewQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/domain/product/productreview/ProductReviewRepository.java
  src/main/java/com/farmer/backend/domain/product/productreview/ProductReviews.java
  src/main/java/com/farmer/backend/domain/product/productreviewstar/ProductReviewAverage.java
  src/main/java/com/farmer/backend/domain/product/productreviewstar/ProductReviewAverageRepository.java
  src/test/java/com/farmer/backend/api/controller/review/ReviewControllerTest.java
  src/test/java/com/farmer/backend/api/service/review/ReviewServiceTest.java
Labels: test, refactor, feature

#96 Feature/user/search : 검색 기능
  src/main/java/com/farmer/backend/api/controller/qna/QnAController.java
  src/main/java/com/farmer/backend/api/controller/qna/response/ResponseProductQnADto.java
  src/main/java/com/farmer/backend/api/controller/review/ReviewController.java
  src/main/java/com/farmer/backend/api/controller/search/SearchController.java
  src/main/java/com/farmer/backend/api/controller/search/request/RequestSearchDto.java
  src/main/java/com/farmer/backend/api/controller/search/request/SearchProductCondition.java
  src/main/java/com/farmer/backend/api/controller/search/response/ResponseSearchProductDto.java
  src/main/java/com/farmer/backend/api/service/qna/ProductQnAService.java
  src/main/java/com/farmer/backend/api/service/search/SearchService.java
  src/main/java/com/farmer/backend/domain/admin/qna/Qna.java
  src/main/java/com/farmer/backend/domain/admin/qna/SecretQuestion.java
  src/main/java/com/farmer/backend/domain/qna/ProductQnAQueryRepository.java
  src/main/java/com/farmer/backend/domain/qna/ProductQnAQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/domain/search/Search.java
  src/main/java/com/farmer/backend/domain/search/SearchQueryRepository.java
  src/main/java/com/farmer/backend/domain/search/SearchQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/exception/ErrorCode.java
  src/main/java/com/farmer/backend/jwt/JwtAuthenticationProcessingFilter.java
  src/main/java/com/farmer/backend/jwt/JwtService.java
Labels: feature

#93 feature/user/qna : 상품별 문의사항 전체리스트 출력
  src/main/java/com/farmer/backend/api/controller/qna/QnAController.java
  src/main/java/com/farmer/backend/api/controller/qna/response/ResponseProductQnADto.java
  src/main/java/com/farmer/backend/api/controller/review/ReviewController.java
  src/main/java/com/farmer/backend/api/service/qna/ProductQnAService.java
  src/main/java/com/farmer/backend/domain/admin/qna/Qna.java
  src/main/java/com/farmer/backend/domain/admin/qna/SecretQuestion.java
  src/main/java/com/farmer/backend/domain/qna/ProductQnAQueryRepository.java
  src/main/java/com/farmer/backend/domain/qna/ProductQnAQueryRepositoryImpl.java
Labels: feature

#97 Feature/member/orders : 주문, 배송 도메인 기능 개발
  src/main/java/com/farmer/backend/api/controller/cart/CartController.java
  src/main/java/com/farmer/backend/api/controller/cart/request/RequestProductCartDto.java
  src/main/java/com/farmer/backend/api/controller/coupon/CouponController.java
  src/main/java/com/farmer/backend/api/controller/coupon/response/ResponseMembersCouponDto.java
  src/main/java/com/farmer/backend/api/controller/member/response/ResponseMemberPoint.java
  src/main/java/com/farmer/backend/api/controller/news/NewsController.java
  src/main/java/com/farmer/backend/api/controller/order/OrderController.java
  src/main/java/com/farmer/backend/api/controller/order/response/ResponseOrderInfoDto.java
  src/main/java/com/farmer/backend/api/controller/orderproduct/OrderProductController.java
  src/main/java/com/farmer/backend/api/controller/orderproduct/request/RequestOrderProductList.java
  src/main/java/com/farmer/backend/api/controller/orderproduct/response/ResponseOrderProductListDto.java
  src/main/java/com/farmer/backend/api/controller/payment/PaymentController.java
  src/main/java/com/farmer/backend/api/controller/product/ProductController.java
  src/main/java/com/farmer/backend/api/controller/productcategory/ProductCategoryController.java
  src/main/java/com/farmer/backend/api/service/cart/CartService.java
  src/main/java/com/farmer/backend/api/service/member/MemberService.java
  src/main/java/com/farmer/backend/api/service/membersCoupon/membersCouponService.java
  src/main/java/com/farmer/backend/api/service/order/OrderService.java
  src/main/java/com/farmer/backend/api/service/orderproduct/OrderProductService.java
  src/main/java/com/farmer/backend/domain/cart/CartQueryRepository.java
  src/main/java/com/farmer/backend/domain/cart/CartQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/domain/cart/CartRepository.java
  src/main/java/com/farmer/backend/domain/delivery/Delivery.java
  src/main/java/com/farmer/backend/domain/delivery/DeliveryMemo.java
  src/main/java/com/farmer/backend/domain/deliveryaddress/DeliveryAddressRepository.java
  src/main/java/com/farmer/backend/domain/memberscoupon/MembersCouponQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/domain/orderproduct/OrderProductQueryRepositoryImpl.java
  src/test/java/com/farmer/backend/api/controller/orderproduct/OrderProductControllerTest.java
  src/test/java/com/farmer/backend/api/service/member/MemberServiceTest.java
  src/test/java/com/farmer/backend/api/service/membersCoupon/membersCouponServiceTest.java
  src/test/java/com/farmer/backend/api/service/orderproduct/OrderProductServiceTest.java
  src/test/java/com/farmer/backend/service/admin/MemberServiceTest.java
Labels: bug, feature

#85 Feature/user/order-product: 주문조회 날짜 데이터 NPE 오류 수정
  src/main/java/com/farmer/backend/api/controller/orderproduct/OrderProductController.java
  src/main/java/com/farmer/backend/api/service/orderproduct/OrderProductService.java
  src/main/java/com/farmer/backend/domain/orderproduct/OrderProductQueryRepositoryImpl.java
  src/test/java/com/farmer/backend/api/controller/orderproduct/OrderProductControllerTest.java
Labels: bug, refactor

#104 Feature/member/orders : Swagger UI 경로 변경
  src/main/resources/application.yml
Labels: setting, refactor

#105 Feature/member/orders : Swagger-UI 경로 변경
  src/main/resources/application.yml
Labels: setting, refactor

#107 Feature/member/orders: jwt 인증 방식으로 인한 Swagger-ui 경로 변경
  src/main/resources/application.yml
Labels: bug, setting

#108 Feature/user/member : 닉네임 중복확인
  src/main/java/com/farmer/backend/api/controller/member/MemberController.java
  src/main/java/com/farmer/backend/api/service/member/MemberService.java
Labels: bug, refactor

#114 Feature/user/member : 프로필 수정, 베스트 리뷰, 검색 기능 수정
  src/main/java/com/farmer/backend/api/controller/join/JoinController.java
  src/main/java/com/farmer/backend/api/controller/member/MemberController.java
  src/main/java/com/farmer/backend/api/controller/member/request/RequestMemberProfileDto.java
  src/main/java/com/farmer/backend/api/controller/review/response/ResponseBestReviewListDto.java
  src/main/java/com/farmer/backend/api/controller/search/SearchController.java
  src/main/java/com/farmer/backend/api/controller/search/response/ResponseSearchPage.java
  src/main/java/com/farmer/backend/api/service/member/MemberService.java
  src/main/java/com/farmer/backend/api/service/search/SearchService.java
  src/main/java/com/farmer/backend/domain/member/Member.java
  src/main/java/com/farmer/backend/domain/product/productreview/ProductReviewQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/domain/search/SearchQueryRepository.java
  src/main/java/com/farmer/backend/domain/search/SearchQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/domain/search/SearchRepository.java
  src/test/java/com/farmer/backend/api/service/member/MemberServiceTest.java
Labels: test, refactor, feature

#115 Feature/user/member : 프로필 수정, 베스트 리뷰, 검색 기능 수정
  src/main/java/com/farmer/backend/api/controller/join/JoinController.java
  src/main/java/com/farmer/backend/api/controller/member/MemberController.java
  src/main/java/com/farmer/backend/api/controller/member/request/RequestMemberProfileDto.java
  src/main/java/com/farmer/backend/api/controller/review/response/ResponseBestReviewListDto.java
  src/main/java/com/farmer/backend/api/controller/search/SearchController.java
  src/main/java/com/farmer/backend/api/controller/search/response/ResponseSearchPage.java
  src/main/java/com/farmer/backend/api/service/member/MemberService.java
  src/main/java/com/farmer/backend/api/service/search/SearchService.java
  src/main/java/com/farmer/backend/domain/member/Member.java
  src/main/java/com/farmer/backend/domain/product/productreview/ProductReviewQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/domain/search/SearchQueryRepository.java
  src/main/java/com/farmer/backend/domain/search/SearchQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/domain/search/SearchRepository.java
  src/test/java/com/farmer/backend/api/service/member/MemberServiceTest.java
Labels: test, refactor, feature

#117 Feature/user/search : 검색어 저장 기능 버그 수정
  src/main/java/com/farmer/backend/api/controller/search/response/ResponseSearchPage.java
  src/main/java/com/farmer/backend/api/service/search/SearchService.java
Labels: bug

#122 Feat/user/qna : page 반환 값 size 고정
  src/main/java/com/farmer/backend/api/controller/qna/QnAController.java
  src/main/java/com/farmer/backend/api/controller/review/ReviewController.java
Labels: refactor

#123 Feature/member/orders : 카테고리별 상품 리스트 조회 기능 개발
  build.gradle
  src/main/java/com/farmer/backend/api/controller/orderproduct/OrderProductController.java
  src/main/java/com/farmer/backend/api/controller/product/ProductController.java
  src/main/java/com/farmer/backend/api/service/product/ProductService.java
  src/main/java/com/farmer/backend/config/S3Config.java
  src/main/java/com/farmer/backend/domain/product/ProductQueryRepository.java
  src/main/java/com/farmer/backend/domain/product/ProductQueryRepositoryImpl.java
  src/test/java/com/farmer/backend/api/service/product/ProductServiceTest.java
Labels: bug, feature, performance

#125 feat/user/joinLogin : 소셜 로그인 회원 토큰 오류
  src/main/java/com/farmer/backend/login/oauth/userInfo/GoogleSocialLogin.java
  src/main/java/com/farmer/backend/login/oauth/userInfo/KakaoSocialLogin.java
  src/main/java/com/farmer/backend/login/oauth/userInfo/NaverSocialLogin.java
Labels: bug

#129 fix: Product 도메인 별점의 대한 리스트 출력 수정
  src/main/java/com/farmer/backend/domain/product/Product.java
  src/main/java/com/farmer/backend/domain/product/ProductQueryRepositoryImpl.java
  src/test/java/com/farmer/backend/api/service/product/ProductServiceTest.java
Labels: bug

#130 fix: Product 도메인 별점의 대한 리스트 출력 수정
  build.gradle
  src/main/java/com/farmer/backend/api/controller/banner/response/ResponseBannerDtoList.java
  src/main/java/com/farmer/backend/api/controller/orderproduct/OrderProductController.java
  src/main/java/com/farmer/backend/api/controller/product/ProductController.java
  src/main/java/com/farmer/backend/api/controller/product/response/ResponseProductDtoList.java
  src/main/java/com/farmer/backend/api/controller/qna/QnAController.java
  src/main/java/com/farmer/backend/api/controller/review/ReviewController.java
  src/main/java/com/farmer/backend/api/controller/search/SearchController.java
  src/main/java/com/farmer/backend/api/controller/search/request/SearchProductCondition.java
  src/main/java/com/farmer/backend/api/service/product/ProductService.java
  src/main/java/com/farmer/backend/api/service/review/ReviewService.java
  src/main/java/com/farmer/backend/api/service/search/SearchService.java
  src/main/java/com/farmer/backend/domain/banner/BannerQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/domain/product/ProductQueryRepository.java
  src/main/java/com/farmer/backend/domain/product/ProductQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/domain/product/productreview/ProductReviewQueryRepository.java
  src/main/java/com/farmer/backend/domain/product/productreview/ProductReviewQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/domain/qna/ProductQnAQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/login/oauth/userInfo/GoogleSocialLogin.java
  src/main/java/com/farmer/backend/login/oauth/userInfo/KakaoSocialLogin.java
  src/main/java/com/farmer/backend/login/oauth/userInfo/NaverSocialLogin.java
  src/main/resources/application.yml
  src/test/java/com/farmer/backend/api/service/product/ProductServiceTest.java
  src/test/java/com/farmer/backend/api/service/review/ReviewServiceTest.java
Labels: bug

#135 Feature/user/qna : 문의 사항 작성, 문의 사항 상세보기
  src/main/java/com/farmer/backend/api/controller/member/MemberController.java
  src/main/java/com/farmer/backend/api/controller/qna/QnAController.java
  src/main/java/com/farmer/backend/api/controller/qna/request/RequestQnAWriteDto.java
  src/main/java/com/farmer/backend/api/controller/qna/response/ResponseProductQnADto.java
  src/main/java/com/farmer/backend/api/controller/qna/response/ResponseQnADetailDto.java
  src/main/java/com/farmer/backend/api/service/member/MemberService.java
  src/main/java/com/farmer/backend/api/service/qna/ProductQnAService.java
  src/main/java/com/farmer/backend/domain/qna/ProductQnAQueryRepository.java
  src/main/java/com/farmer/backend/domain/qna/ProductQnAQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/exception/ErrorCode.java
  src/test/java/com/farmer/backend/api/controller/qna/QnAControllerTest.java
  src/test/java/com/farmer/backend/api/service/qna/ProductQnAServiceTest.java
Labels: test, feature

#136 Feature/member/orders : 아임포트 라이브러리 추가, YML 암호화
  build.gradle
  src/main/java/com/farmer/backend/BackendApplication.java
  src/main/java/com/farmer/backend/api/controller/iamport/ImportApiController.java
  src/main/java/com/farmer/backend/api/controller/order/response/ResponseOrderInfoDto.java
  src/main/java/com/farmer/backend/api/service/order/OrderService.java
  src/main/java/com/farmer/backend/config/JasyptConfig.java
  src/main/resources/application.yml
Labels: setting, devops, feature

#138 Feature/s3 : S3 설정
  .github/workflows/gradle.yml
  build.gradle
  src/main/java/com/farmer/backend/config/S3Config.java
Labels: setting, devops

#147 Feat/user/qna : 스웨거 operation 수정
  src/main/java/com/farmer/backend/api/controller/qna/QnAController.java
Labels: document

#150 Fix: YML 설정 파일 변경
  src/main/resources/application.yml
Labels: setting

#151 Fix: YML 설정 파일 변경
  src/main/resources/application.yml
Labels: setting

#152 Feature/member/orders : jasypt의 password 환경 변수 등록
  src/main/resources/application.yml
Labels: setting

#153 Feature/member/orders : jasypt의 password 환경 변수 등록
  src/main/resources/application.yml
Labels: setting

#154 Fix: jasypt 비밀번호 재설정
  src/main/resources/application.yml
Labels: setting, devops

#155 Fix: jasypt 비밀번호 재설정
  src/main/resources/application.yml
Labels: setting, devops

#156 Feature/s3 : s3제거
  .github/workflows/gradle.yml
  build.gradle
  src/main/java/com/farmer/backend/api/controller/review/ReviewController.java
  src/main/java/com/farmer/backend/api/service/S3Service.java
  src/main/java/com/farmer/backend/api/service/review/ReviewService.java
  src/main/java/com/farmer/backend/config/S3Config.java
  src/main/resources/application.yml
Labels: bug

#158 fix: YML 설정 변경
  build.gradle
  src/main/resources/application.yml
Labels: setting

#159 Feature/s3 : s3 추가
  build.gradle
  src/main/java/com/farmer/backend/api/controller/review/ReviewController.java
  src/main/java/com/farmer/backend/api/service/S3Service.java
  src/main/java/com/farmer/backend/api/service/review/ReviewService.java
  src/main/java/com/farmer/backend/config/S3Config.java
  src/main/resources/application.yml
Labels: bug

#157 Feat/S3 : S3제거
  build.gradle
  src/main/java/com/farmer/backend/api/service/review/ReviewService.java
  src/main/resources/application.yml
Labels: bug

#160 fix: S3 배포 오류 수정
  appspec.yml
Labels: devops

#161 Fix: S3 배포 오류 수정
  appspec.yml
Labels: devops

#162 Fix: appspec 설정 정보 변경
  appspec.yml
Labels: devops

#163 Fix: appspec 설정 정보 변경
  appspec.yml
Labels: devops

#164 Feat: CodeDeploy 파일 덮어쓰기
  appspec.yml
Labels: devops

#165 Feat: CodeDeploy 파일 덮어쓰기
  appspec.yml
Labels: devops

#166 Feature/s3 : s3 수정
  src/main/java/com/farmer/backend/api/controller/review/ReviewController.java
  src/main/java/com/farmer/backend/api/service/S3Service.java
  src/main/java/com/farmer/backend/api/service/review/ReviewService.java
  src/main/java/com/farmer/backend/config/S3Config.java
Labels: bug

#168 Feature/s3 : s3 수정
  .github/workflows/gradle.yml
  appspec.yml
  build.gradle
  src/main/java/com/farmer/backend/api/controller/review/ReviewController.java
  src/main/java/com/farmer/backend/api/service/S3Service.java
  src/main/java/com/farmer/backend/api/service/review/ReviewService.java
  src/main/java/com/farmer/backend/config/S3Config.java
Labels: bug, feature

#170 Feat/S3 : s3 yml 암호화
  .github/workflows/gradle.yml
Labels: bug

#174 Feat/user/qna : QNA 상세보기 TEST 오류 해결
  src/test/java/com/farmer/backend/api/service/qna/ProductQnAServiceTest.java
Labels: bug

#176 Feat/user/qna : 장바구니 TEST 오류 해결
  src/test/java/com/farmer/backend/api/service/cart/CartServiceTest.java
Labels: bug, test

#177 Feat/user/qna : 장바구니 테스트 오류 해결
  .github/workflows/gradle.yml
  build.gradle
  src/main/java/com/farmer/backend/api/controller/review/ReviewController.java
  src/main/java/com/farmer/backend/api/service/S3Service.java
  src/main/java/com/farmer/backend/api/service/review/ReviewService.java
  src/main/java/com/farmer/backend/config/S3Config.java
  src/test/java/com/farmer/backend/api/controller/qna/QnAControllerTest.java
  src/test/java/com/farmer/backend/api/service/cart/CartServiceTest.java
  src/test/java/com/farmer/backend/api/service/qna/ProductQnAServiceTest.java
Labels: bug, test

#178 Feature/member/orders : S3 빈 등록 에러로 인한 의존성 제거, 관련 로직 삭제
  build.gradle
  src/main/java/com/farmer/backend/api/controller/review/ReviewController.java
  src/main/java/com/farmer/backend/api/service/S3Service.java
  src/main/java/com/farmer/backend/api/service/review/ReviewService.java
  src/main/java/com/farmer/backend/config/S3Config.java
Labels: devops

#183 fix : gradle.yml 수정
  .github/workflows/gradle.yml
Labels: bug

#186 Feature/s3 : S3 재설정
  build.gradle
  src/main/java/com/farmer/backend/api/controller/review/ReviewController.java
  src/main/java/com/farmer/backend/api/service/review/ReviewService.java
  src/main/java/com/farmer/backend/config/S3Config.java
Labels: bug

#187 fix : S3 재설정
  build.gradle
  src/main/java/com/farmer/backend/api/controller/review/ReviewController.java
  src/main/java/com/farmer/backend/api/service/review/ReviewService.java
  src/main/java/com/farmer/backend/config/S3Config.java
Labels: bug

#188 fix: S3 의존성 수정
  .github/workflows/gradle.yml
  build.gradle
Labels: bug

#189 fix : s3 의존성 수정
  .github/workflows/gradle.yml
  build.gradle
Labels: bug

#190 fix: S3 yml 수정
  .github/workflows/gradle.yml
Labels: bug

#191 fix : s3 yml 수정
  .github/workflows/gradle.yml
Labels: bug

#193 Feat: 주문 생성 로직 추가
  src/main/java/com/farmer/backend/api/controller/order/OrderController.java
Labels: test, feature

#194 Feat: 주문 생성 로직 추가
  src/main/java/com/farmer/backend/api/controller/order/OrderController.java
Labels: test, feature

#195 fix : build.gradle 수정
  .github/workflows/gradle.yml
Labels: bug
