Repository TeamProject-Farmer/back-end, pull requests merged in 2023-09, with the labels that each got.

#297 Feature/member/orders: 주문/결제 API 수정
  build.gradle
  src/main/java/com/farmer/backend/api/service/order/OrderService.java
  src/main/resources/application-jwt.yml
  src/test/java/com/farmer/backend/api/service/cart/CartServiceTest.java
Labels: bug

#299 Feature/member/orders: 의존성 에러 수정
  build.gradle
Labels: bug, setting

#298 Feature/member/orders: 주문/결제 API 수정
  build.gradle
  src/main/java/com/farmer/backend/api/service/order/OrderService.java
  src/main/resources/application-jwt.yml
  src/test/java/com/farmer/backend/api/service/cart/CartServiceTest.java
Labels: bug

#300 Feature/user/member : jwt.yml 수정
  .DS_Store
  src/.DS_Store
  src/main/.DS_Store
  src/main/resources/application-jwt.yml
Labels: bug

#302 Feature/user/member : jwt.yml 오류 수정
  src/main/resources/application-jwt.yml
Labels: bug

#303 Feature/user/member : jwt.yml 오류 수정
  .DS_Store
  src/.DS_Store
  src/main/.DS_Store
  src/main/resources/application-jwt.yml
Labels: bug

#306 Feature/user/review : 리뷰 평점 오류 메세지 수정
  src/main/java/com/farmer/backend/api/service/review/ReviewService.java
  src/main/java/com/farmer/backend/domain/product/productreview/ProductReviewQueryRepository.java
  src/main/java/com/farmer/backend/domain/product/productreview/ProductReviewQueryRepositoryImpl.java
Labels: refactor

#310 feat/user/member : 회원 적립금 조회 테스트 코드 수정
  src/test/java/com/farmer/backend/api/service/member/MemberServiceTest.java
Labels: bug

#309 Feature/user/member : 첫 소셜 로그인 회원 쿠폰 부여, 소셜 로그인 회원 토큰 업데이트
  src/main/java/com/farmer/backend/login/oauth/userInfo/GoogleSocialLogin.java
  src/main/java/com/farmer/backend/login/oauth/userInfo/KakaoSocialLogin.java
  src/main/java/com/farmer/backend/login/oauth/userInfo/NaverSocialLogin.java
  src/test/java/com/farmer/backend/api/service/member/MemberServiceTest.java
Labels: bug

#311 faet/user/member : 소셜 로그인 redirect uri 변경
  src/main/resources/application-oauth.yml
Labels: refactor

#312 faet/user/member : 소셜 로그인 redirect uri 변경
  src/main/resources/application-oauth.yml
Labels: refactor

#313 Feature/user/member : 소셜 로그인 반환값 수정
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/com/farmer/backend/api/controller/user/login/ResponseOAuthUserInfoDto.java
  src/main/java/com/farmer/backend/api/service/member/MemberService.java
  src/main/java/com/farmer/backend/jwt/JwtService.java
Labels: refactor

#314 Feature/user/member : 소셜 로그인 반환값 수정
  src/main/java/com/farmer/backend/api/controller/user/login/ResponseOAuthUserInfoDto.java
  src/main/java/com/farmer/backend/api/service/member/MemberService.java
  src/main/java/com/farmer/backend/jwt/JwtService.java
Labels: refactor

#315 feat/user/member : 배포주소 cors 설정
  src/main/java/com/farmer/backend/config/WebMvcConfig.java
Labels: bug

#317 feat/user/member : redirect uri 재설정
  src/main/resources/application-oauth.yml
Labels: bug

#316 feat/user/member : 배포주소 cors 설정
  src/main/java/com/farmer/backend/config/WebMvcConfig.java
  src/main/resources/application-oauth.yml
Labels: bug

#318 fix: 상품의 옵션이 존재하지 않을때에도 장바구니에 데이터 추가
  src/main/java/com/farmer/backend/api/service/cart/CartService.java
Labels: bug, performance

#319 Feature/admin/orders: 장바구니 상품 추가 API 수정
  src/main/java/com/farmer/backend/api/service/cart/CartService.java
Labels: bug, performance

#321 Feature/admin/orders: 어드민 주문관리 페이지 주문상세정보 API 개발
  src/main/java/com/farmer/backend/api/controller/AdminApiController.java
  src/main/java/com/farmer/backend/api/controller/admin/order/OrderController.java
  src/main/java/com/farmer/backend/api/controller/admin/order/response/ResponseOrderDetailDto.java
  src/main/java/com/farmer/backend/api/service/cart/CartService.java
  src/main/java/com/farmer/backend/api/service/order/OrderService.java
  src/main/java/com/farmer/backend/domain/orders/OrderQueryRepository.java
  src/main/java/com/farmer/backend/domain/orders/OrderQueryRepositoryImpl.java
Labels: feature, performance

#324 feat/user/product : 상품 리뷰, 문의사항 개수, 리뷰 평점 정보 출력
  src/main/java/com/farmer/backend/api/controller/user/product/ProductController.java
  src/main/java/com/farmer/backend/api/controller/user/product/response/ResponseReviewAndQnaDto.java
  src/main/java/com/farmer/backend/api/service/product/ProductService.java
  src/main/java/com/farmer/backend/domain/product/ProductQueryRepository.java
  src/main/java/com/farmer/backend/domain/product/ProductQueryRepositoryImpl.java
Labels: feature
