Repository TeamProject-Farmer/back-end, pull requests merged in 2023-08, with the labels that each got.

#197 Feat/user/member : 쿠폰 사용 기능 추가
  src/main/java/com/farmer/backend/api/controller/coupon/CouponController.java
  src/main/java/com/farmer/backend/api/controller/coupon/response/ResponseUseCouponListDto.java
  src/main/java/com/farmer/backend/api/controller/review/response/ResponseBestReviewListDto.java
  src/main/java/com/farmer/backend/api/service/membersCoupon/membersCouponService.java
  src/main/java/com/farmer/backend/domain/memberscoupon/MembersCouponQueryRepository.java
  src/main/java/com/farmer/backend/domain/memberscoupon/MembersCouponQueryRepositoryImpl.java
Labels: feature

#198 Feat/user/member : 쿠폰 사용 기능
  src/main/java/com/farmer/backend/api/controller/coupon/CouponController.java
  src/main/java/com/farmer/backend/api/controller/coupon/response/ResponseUseCouponListDto.java
  src/main/java/com/farmer/backend/api/controller/review/response/ResponseBestReviewListDto.java
  src/main/java/com/farmer/backend/api/service/membersCoupon/membersCouponService.java
  src/main/java/com/farmer/backend/domain/memberscoupon/MembersCouponQueryRepository.java
  src/main/java/com/farmer/backend/domain/memberscoupon/MembersCouponQueryRepositoryImpl.java
Labels: feature

#199 Feature/member/orders : 회원 보유 적립금 조회 기능 개발
  src/main/java/com/farmer/backend/api/controller/member/MemberController.java
  src/test/java/com/farmer/backend/api/service/member/MemberServiceTest.java
Labels: feature

#201 Feature/member/orders : 회원 보유 적립금 조회 기능 개발
  src/main/java/com/farmer/backend/api/controller/member/MemberController.java
  src/test/java/com/farmer/backend/api/service/member/MemberServiceTest.java
Labels: feature

#202 fix: yml 파일 분리, DB source 암호화
  src/main/resources/application.yml
Labels: setting, devops

#205 Fix: database.yml gitignore 해제
  .gitignore
  src/main/resources/application-database.yml
Labels: setting

#204 fix: yml 파일 분리, DB source 암호화
  .github/workflows/gradle.yml
  .gitignore
  src/main/resources/application-database.yml
  src/main/resources/application.yml
Labels: setting, devops

#206 Fix: database.yml 제거
  .gitignore
  gradlew
  src/main/resources/application-database.yml
  src/main/resources/application.yml
Labels: setting

#207 Fix: database.yml 제거
  .gitignore
  gradlew
  src/main/resources/application-database.yml
  src/main/resources/application.yml
Labels: setting

#208 Remove: jasypt 의존성 제거 및 config 파일 삭제
  build.gradle
  src/main/java/com/farmer/backend/config/JasyptConfig.java
Labels: setting

#209 Remove: jasypt 의존성 제거 및 config 파일 삭제
  build.gradle
  src/main/java/com/farmer/backend/config/JasyptConfig.java
Labels: setting

#210 Remove: application jayspt 주석 제거
  src/main/java/com/farmer/backend/BackendApplication.java
Labels: setting

#211 Remove: application jayspt 주석 제거
  src/main/java/com/farmer/backend/BackendApplication.java
Labels: setting

#212 Feature/member/orders : 상품 도메인 md pick, 기획전 상품 조회 기능 개발
  .github/workflows/gradle.yml
  src/main/java/com/farmer/backend/api/controller/product/ProductController.java
  src/main/java/com/farmer/backend/api/controller/product/response/ResponseProductDtoList.java
  src/main/java/com/farmer/backend/api/service/product/ProductService.java
  src/main/java/com/farmer/backend/domain/news/News.java
  src/main/java/com/farmer/backend/domain/product/ProductDivision.java
  src/main/java/com/farmer/backend/domain/product/ProductQueryRepository.java
  src/main/java/com/farmer/backend/domain/product/ProductQueryRepositoryImpl.java
  src/test/java/com/farmer/backend/api/service/cart/CartServiceTest.java
  src/test/java/com/farmer/backend/api/service/news/NewsServiceTest.java
  src/test/java/com/farmer/backend/api/service/orderproduct/OrderProductServiceTest.java
  src/test/java/com/farmer/backend/api/service/product/ProductServiceTest.java
Labels: test, feature

#214 Feature/member/orders : 상품 도메인 md pick, 기획전 상품 조회 기능 개발
  src/main/java/com/farmer/backend/api/controller/product/ProductController.java
  src/main/java/com/farmer/backend/api/controller/product/response/ResponseProductDtoList.java
  src/main/java/com/farmer/backend/api/service/product/ProductService.java
  src/main/java/com/farmer/backend/domain/news/News.java
  src/main/java/com/farmer/backend/domain/product/ProductDivision.java
  src/main/java/com/farmer/backend/domain/product/ProductQueryRepository.java
  src/main/java/com/farmer/backend/domain/product/ProductQueryRepositoryImpl.java
  src/test/java/com/farmer/backend/api/service/cart/CartServiceTest.java
  src/test/java/com/farmer/backend/api/service/membersCoupon/membersCouponServiceTest.java
  src/test/java/com/farmer/backend/api/service/news/NewsServiceTest.java
  src/test/java/com/farmer/backend/api/service/orderproduct/OrderProductServiceTest.java
  src/test/java/com/farmer/backend/api/service/product/ProductServiceTest.java
Labels: test, feature, performance

#218 Feature/user/review : 리뷰 작성 오류 수정
  src/main/java/com/farmer/backend/api/controller/banner/response/ResponseBannerDtoList.java
  src/main/java/com/farmer/backend/api/controller/coupon/CouponController.java
  src/main/java/com/farmer/backend/api/controller/coupon/response/ResponseUseCouponListDto.java
  src/main/java/com/farmer/backend/api/controller/review/ReviewController.java
  src/main/java/com/farmer/backend/api/service/membersCoupon/membersCouponService.java
  src/main/java/com/farmer/backend/api/service/review/ReviewService.java
  src/main/java/com/farmer/backend/domain/memberscoupon/MemberCouponRepository.java
  src/main/java/com/farmer/backend/domain/memberscoupon/MembersCouponQueryRepository.java
  src/main/java/com/farmer/backend/domain/memberscoupon/MembersCouponQueryRepositoryImpl.java
  src/test/java/com/farmer/backend/api/service/membersCoupon/MembersCouponServiceTest.java
  src/test/java/com/farmer/backend/api/service/membersCoupon/membersCouponServiceTest.java
Labels: bug, feature

#220 Feat/user/review : 테스트 오류 수정
  src/test/java/com/farmer/backend/api/service/cart/CartServiceTest.java
  src/test/java/com/farmer/backend/api/service/review/ReviewServiceTest.java
Labels: bug, test

#221 Feat/user/review : 테스트 오류 수정
  src/main/java/com/farmer/backend/api/controller/banner/response/ResponseBannerDtoList.java
  src/main/java/com/farmer/backend/api/controller/coupon/CouponController.java
  src/main/java/com/farmer/backend/api/controller/coupon/response/ResponseUseCouponListDto.java
  src/main/java/com/farmer/backend/api/controller/review/ReviewController.java
  src/main/java/com/farmer/backend/api/service/membersCoupon/membersCouponService.java
  src/main/java/com/farmer/backend/api/service/review/ReviewService.java
  src/main/java/com/farmer/backend/domain/memberscoupon/MemberCouponRepository.java
  src/main/java/com/farmer/backend/domain/memberscoupon/MembersCouponQueryRepository.java
  src/main/java/com/farmer/backend/domain/memberscoupon/MembersCouponQueryRepositoryImpl.java
  src/test/java/com/farmer/backend/api/service/cart/CartServiceTest.java
  src/test/java/com/farmer/backend/api/service/membersCoupon/MembersCouponServiceTest.java
  src/test/java/com/farmer/backend/api/service/membersCoupon/membersCouponServiceTest.java
  src/test/java/com/farmer/backend/api/service/review/ReviewServiceTest.java
Labels: bug, test

#224 Feature/member/orders: 아임포트 라이브러리를 활용한 결제 요청
  src/main/java/com/farmer/backend/api/controller/cart/CartController.java
  src/main/java/com/farmer/backend/api/controller/cart/response/ResponseCartProductListDto.java
  src/main/java/com/farmer/backend/api/controller/iamport/ImportApiController.java
  src/main/java/com/farmer/backend/domain/cart/CartQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/domain/product/productreview/ProductReviewQueryRepositoryImpl.java
  src/main/resources/templates/IamportOrderPage.html
Labels: bug, feature

#225 Feature/user/review : 상품 리뷰 , 상품 리뷰 별점 기능 수정
  src/main/java/com/farmer/backend/api/controller/review/request/RequestReviewStarDto.java
  src/main/java/com/farmer/backend/api/controller/review/response/ResponseProductReviewListDto.java
  src/main/java/com/farmer/backend/api/service/review/ReviewService.java
  src/main/java/com/farmer/backend/domain/options/Options.java
  src/main/java/com/farmer/backend/domain/orderproduct/OrderProductRepository.java
  src/main/java/com/farmer/backend/domain/product/productreview/ProductReviewQueryRepository.java
  src/main/java/com/farmer/backend/domain/product/productreview/ProductReviewQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/domain/product/productreview/ProductReviewRepository.java
Labels: bug

#226 Feat/user/review : 상품 리뷰 , 상품 리뷰 별점 기능 수정
  src/main/java/com/farmer/backend/api/controller/review/request/RequestReviewStarDto.java
  src/main/java/com/farmer/backend/api/controller/review/response/ResponseProductReviewListDto.java
  src/main/java/com/farmer/backend/api/service/review/ReviewService.java
  src/main/java/com/farmer/backend/domain/options/Options.java
  src/main/java/com/farmer/backend/domain/orderproduct/OrderProductRepository.java
  src/main/java/com/farmer/backend/domain/product/productreview/ProductReviewQueryRepository.java
  src/main/java/com/farmer/backend/domain/product/productreview/ProductReviewQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/domain/product/productreview/ProductReviewRepository.java
Labels: bug

#227 Feat/user/qna : 상품별 문의사항 리스트 추가
  src/main/java/com/farmer/backend/api/controller/qna/QnAController.java
  src/main/java/com/farmer/backend/api/service/qna/ProductQnAService.java
  src/main/java/com/farmer/backend/domain/qna/ProductQnAQueryRepository.java
  src/main/java/com/farmer/backend/domain/qna/ProductQnAQueryRepositoryImpl.java
  src/test/java/com/farmer/backend/api/controller/qna/QnAControllerTest.java
  src/test/java/com/farmer/backend/api/service/qna/ProductQnAServiceTest.java
Labels: feature

#228 Feat/user/qna : 상품별 문의사항 리스트 추가
  src/main/java/com/farmer/backend/api/controller/qna/QnAController.java
  src/main/java/com/farmer/backend/api/service/qna/ProductQnAService.java
  src/main/java/com/farmer/backend/domain/qna/ProductQnAQueryRepository.java
  src/main/java/com/farmer/backend/domain/qna/ProductQnAQueryRepositoryImpl.java
  src/test/java/com/farmer/backend/api/controller/qna/QnAControllerTest.java
  src/test/java/com/farmer/backend/api/service/qna/ProductQnAServiceTest.java
Labels: feature

#229 Feat/user/review : 리뷰 '좋아요' 기능 추가
  src/main/java/com/farmer/backend/api/controller/review/ReviewController.java
  src/main/java/com/farmer/backend/api/controller/review/response/ResponseProductReviewListDto.java
  src/main/java/com/farmer/backend/api/service/review/ReviewService.java
  src/main/java/com/farmer/backend/domain/product/productreview/ProductReviewQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/domain/product/productreview/ProductReviewRepository.java
  src/main/java/com/farmer/backend/domain/product/productreview/ProductReviews.java
Labels: feature

#230 Feat/user/review ; 리뷰 '좋아요' 기능 추가
  src/main/java/com/farmer/backend/api/controller/review/ReviewController.java
  src/main/java/com/farmer/backend/api/controller/review/response/ResponseProductReviewListDto.java
  src/main/java/com/farmer/backend/api/service/review/ReviewService.java
  src/main/java/com/farmer/backend/domain/product/productreview/ProductReviewQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/domain/product/productreview/ProductReviewRepository.java
  src/main/java/com/farmer/backend/domain/product/productreview/ProductReviews.java
Labels: feature

#232 Feature/member/orders : 주문 결제 API 구현
  src/main/java/com/farmer/backend/api/controller/iamport/ImportApiController.java
  src/main/java/com/farmer/backend/api/controller/order/OrderController.java
  src/main/java/com/farmer/backend/api/controller/order/request/RequestOrderInfoDto.java
  src/main/java/com/farmer/backend/api/controller/orderproduct/request/RequestOrderProductList.java
  src/main/java/com/farmer/backend/api/controller/product/ProductController.java
  src/main/java/com/farmer/backend/api/service/order/OrderService.java
  src/main/java/com/farmer/backend/api/service/product/ProductService.java
  src/main/java/com/farmer/backend/domain/delivery/Delivery.java
  src/main/java/com/farmer/backend/domain/delivery/DeliveryRepository.java
  src/main/java/com/farmer/backend/domain/deliveryaddress/DeliveryAddress.java
  src/main/java/com/farmer/backend/domain/deliveryaddress/DeliveryAddressQueryRepository.java
  src/main/java/com/farmer/backend/domain/deliveryaddress/DeliveryAddressQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/domain/deliveryaddress/DeliveryAddressRepository.java
  src/main/java/com/farmer/backend/domain/orders/Orders.java
  src/main/java/com/farmer/backend/domain/product/ProductQueryRepository.java
  src/main/java/com/farmer/backend/domain/product/ProductQueryRepositoryImpl.java
  src/main/resources/templates/IamportOrderPage.html
  src/test/java/com/farmer/backend/api/service/cart/CartServiceTest.java
Labels: feature, performance

#234 Feature/member/orders: 장바구니 상품 수량 변경 테스트 기존 데이터 삭제로 인한 수정 코드 작성
  src/test/java/com/farmer/backend/api/service/cart/CartServiceTest.java
Labels: test

#233 Feature/member/orders: 주문 결제 API 구현
  src/main/java/com/farmer/backend/api/controller/iamport/ImportApiController.java
  src/main/java/com/farmer/backend/api/controller/order/OrderController.java
  src/main/java/com/farmer/backend/api/controller/order/request/RequestOrderInfoDto.java
  src/main/java/com/farmer/backend/api/controller/orderproduct/request/RequestOrderProductList.java
  src/main/java/com/farmer/backend/api/controller/product/ProductController.java
  src/main/java/com/farmer/backend/api/service/order/OrderService.java
  src/main/java/com/farmer/backend/api/service/product/ProductService.java
  src/main/java/com/farmer/backend/domain/delivery/Delivery.java
  src/main/java/com/farmer/backend/domain/delivery/DeliveryRepository.java
  src/main/java/com/farmer/backend/domain/deliveryaddress/DeliveryAddress.java
  src/main/java/com/farmer/backend/domain/deliveryaddress/DeliveryAddressQueryRepository.java
  src/main/java/com/farmer/backend/domain/deliveryaddress/DeliveryAddressQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/domain/deliveryaddress/DeliveryAddressRepository.java
  src/main/java/com/farmer/backend/domain/orders/Orders.java
  src/main/java/com/farmer/backend/domain/product/ProductQueryRepository.java
  src/main/java/com/farmer/backend/domain/product/ProductQueryRepositoryImpl.java
  src/main/resources/templates/IamportOrderPage.html
  src/test/java/com/farmer/backend/api/service/cart/CartServiceTest.java
Labels: feature, performance

#235 Feature/user/review : 리뷰 평점 오류메세지 수정
  src/main/java/com/farmer/backend/api/service/review/ReviewService.java
  src/main/java/com/farmer/backend/domain/product/productreview/ProductReviewQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/exception/ErrorCode.java
Labels: bug

#239 Feature/member/orders: 주문조회 검색 조건 값 수정
  src/main/java/com/farmer/backend/api/controller/orderproduct/OrderProductController.java
  src/main/java/com/farmer/backend/domain/orderproduct/OrderProductQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/domain/orders/OrderStatus.java
  src/main/java/com/farmer/backend/exception/ErrorCode.java
  src/test/java/com/farmer/backend/api/controller/orderproduct/OrderProductControllerTest.java
  src/test/java/com/farmer/backend/api/service/cart/CartServiceTest.java
Labels: bug, performance

#240 Feature/member/orders: 주문/결제 회원 적립금 차감, 주문내역 조회 수정
  src/main/java/com/farmer/backend/api/controller/order/OrderController.java
  src/main/java/com/farmer/backend/api/controller/order/request/RequestOrderInfoDto.java
  src/main/java/com/farmer/backend/api/service/order/OrderService.java
  src/main/java/com/farmer/backend/api/service/orderproduct/OrderProductService.java
  src/main/java/com/farmer/backend/domain/member/Member.java
  src/test/java/com/farmer/backend/api/service/cart/CartServiceTest.java
Labels: bug, feature

#243 Feature/user/join login : jwt 설정
  src/main/java/com/farmer/backend/jwt/JwtAuthenticationProcessingFilter.java
  src/main/java/com/farmer/backend/jwt/JwtService.java
  src/main/resources/application-oauth.yml
Labels: setting, performance

#245 Feat/user/joinLogin : jwt 토큰 만료 오류 메세지 설정
  src/main/java/com/farmer/backend/jwt/JwtService.java
Labels: bug

#246 Feat/user/joinLogin : jwt 토큰 만료 오류 메세지 설정
  src/main/java/com/farmer/backend/jwt/JwtAuthenticationProcessingFilter.java
  src/main/java/com/farmer/backend/jwt/JwtService.java
  src/main/resources/application-oauth.yml
Labels: bug

#247 Feature/member/orders: JWT 토큰 유효시간 테스트를 위한 값 변경
  src/main/resources/application-jwt.yml
Labels: setting

#248 Feature/member/orders: JWT 토큰 유효시간 테스트를 위한 값 변경
  src/main/resources/application-jwt.yml
Labels: setting

#249 feat/user/joinLogin : refresh 토큰 헤더 변경
  src/main/resources/application-jwt.yml
Labels: setting

#250 feat/user/joinLogin : refresh 토큰 헤더 변경
  src/main/resources/application-jwt.yml
Labels: setting

#251 Feature/user/join login : 이메일 인증 , jwt 설정 변경
  src/main/java/com/farmer/backend/api/controller/member/response/ResponseMemberTokenDto.java
  src/main/java/com/farmer/backend/api/service/mail/MailService.java
  src/main/java/com/farmer/backend/jwt/JwtAuthenticationProcessingFilter.java
  src/main/java/com/farmer/backend/jwt/JwtService.java
  src/main/resources/application-jwt.yml
Labels: bug, refactor

#252 Feat/user/joinLogin : 이메일 인증, jwt 설정 변경
  src/main/java/com/farmer/backend/api/controller/member/response/ResponseMemberTokenDto.java
  src/main/java/com/farmer/backend/api/service/mail/MailService.java
  src/main/java/com/farmer/backend/jwt/JwtAuthenticationProcessingFilter.java
  src/main/java/com/farmer/backend/jwt/JwtService.java
  src/main/resources/application-jwt.yml
Labels: bug, refactor

#253 Feature/user/join login : 로그인 반환값 수정, 리뷰 수정사항 반영
  src/main/java/com/farmer/backend/api/controller/review/response/ResponseBestReviewListDto.java
  src/main/java/com/farmer/backend/api/service/review/ReviewService.java
  src/main/java/com/farmer/backend/domain/product/Product.java
  src/main/java/com/farmer/backend/domain/product/productreview/ProductReviewQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/login/general/handler/LoginSuccessHandler.java
Labels: bug

#254 Feature/user/join login : 로그인 반환값 수정, 리뷰 수정사항 반영
  src/main/java/com/farmer/backend/api/controller/review/response/ResponseBestReviewListDto.java
  src/main/java/com/farmer/backend/api/service/review/ReviewService.java
  src/main/java/com/farmer/backend/domain/product/Product.java
  src/main/java/com/farmer/backend/domain/product/productreview/ProductReviewQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/login/general/handler/LoginSuccessHandler.java
Labels: bug

#255 Feat/user/member : 회원가입 시 쿠폰 생성
  src/main/java/com/farmer/backend/api/controller/coupon/CouponController.java
  src/main/java/com/farmer/backend/api/controller/coupon/request/RequestMembersCouponDto.java
  src/main/java/com/farmer/backend/api/service/member/MemberService.java
  src/main/java/com/farmer/backend/api/service/membersCoupon/MembersCouponService.java
  src/main/java/com/farmer/backend/domain/coupon/CouponRepository.java
Labels: feature

#256 Feat/user/member : 회원가입 시 쿠폰 생성
  src/main/java/com/farmer/backend/api/controller/coupon/CouponController.java
  src/main/java/com/farmer/backend/api/controller/coupon/request/RequestMembersCouponDto.java
  src/main/java/com/farmer/backend/api/service/member/MemberService.java
  src/main/java/com/farmer/backend/api/service/membersCoupon/MembersCouponService.java
  src/main/java/com/farmer/backend/domain/coupon/CouponRepository.java
Labels: feature

#257 Feature/member/orders: 결제 요청이 완료된 후 주문 데이터 생성
  src/main/java/com/farmer/backend/api/controller/cart/CartController.java
  src/main/java/com/farmer/backend/api/controller/order/OrderController.java
  src/main/java/com/farmer/backend/api/controller/order/request/RequestOrderInfoDto.java
  src/main/java/com/farmer/backend/api/controller/order/request/RequestOrderProductDto.java
  src/main/java/com/farmer/backend/api/controller/order/response/ResponseDeliveryMemoListDto.java
  src/main/java/com/farmer/backend/api/controller/order/response/ResponseOrderCompleteDto.java
  src/main/java/com/farmer/backend/api/controller/payment/PaymentController.java
  src/main/java/com/farmer/backend/api/controller/payment/request/RequestPaymentInfoDto.java
  src/main/java/com/farmer/backend/api/service/cart/CartService.java
  src/main/java/com/farmer/backend/api/service/order/OrderService.java
  src/main/java/com/farmer/backend/api/service/payment/PaymentService.java
  src/main/java/com/farmer/backend/domain/cart/CartQueryRepository.java
  src/main/java/com/farmer/backend/domain/cart/CartQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/domain/delivery/Delivery.java
  src/main/java/com/farmer/backend/domain/orderproduct/OrderProduct.java
  src/main/java/com/farmer/backend/domain/orders/Orders.java
  src/main/java/com/farmer/backend/exception/ErrorCode.java
Labels: bug, feature, performance

#259 Feature/member/orders: 결제 요청이 완료된 후 주문 데이터 생성
  src/main/java/com/farmer/backend/api/controller/cart/CartController.java
  src/main/java/com/farmer/backend/api/controller/order/OrderController.java
  src/main/java/com/farmer/backend/api/controller/order/request/RequestOrderInfoDto.java
  src/main/java/com/farmer/backend/api/controller/order/request/RequestOrderProductDto.java
  src/main/java/com/farmer/backend/api/controller/order/response/ResponseDeliveryMemoListDto.java
  src/main/java/com/farmer/backend/api/controller/order/response/ResponseOrderCompleteDto.java
  src/main/java/com/farmer/backend/api/controller/payment/PaymentController.java
  src/main/java/com/farmer/backend/api/controller/payment/request/RequestPaymentInfoDto.java
  src/main/java/com/farmer/backend/api/service/cart/CartService.java
  src/main/java/com/farmer/backend/api/service/order/OrderService.java
  src/main/java/com/farmer/backend/api/service/payment/PaymentService.java
  src/main/java/com/farmer/backend/domain/cart/CartQueryRepository.java
  src/main/java/com/farmer/backend/domain/cart/CartQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/domain/delivery/Delivery.java
  src/main/java/com/farmer/backend/domain/orderproduct/OrderProduct.java
  src/main/java/com/farmer/backend/domain/orders/Orders.java
  src/main/java/com/farmer/backend/exception/ErrorCode.java
Labels: bug, feature, performance

#261 Feature/member/orders: 적립금 적용 후 사후처리 검증 추가, 주문자 회원 정보조회 오류 수정
  src/main/java/com/farmer/backend/api/controller/order/OrderController.java
  src/main/java/com/farmer/backend/api/service/order/OrderService.java
  src/main/java/com/farmer/backend/domain/member/Member.java
Labels: bug, refactor, feature, performance

#262 Feature/member/orders: 적립금 적용 후 사후처리 검증 추가, 주문자 회원 정보조회 오류 수정
  src/main/java/com/farmer/backend/api/controller/order/OrderController.java
  src/main/java/com/farmer/backend/api/service/order/OrderService.java
  src/main/java/com/farmer/backend/domain/member/Member.java
Labels: bug, refactor, feature, performance

#263 Feature/user/search : 최근 검색어 , 검색 상품 api 분리
  src/main/java/com/farmer/backend/api/controller/search/SearchController.java
  src/main/java/com/farmer/backend/api/controller/search/response/ResponseSearchPage.java
  src/main/java/com/farmer/backend/api/service/review/ReviewService.java
  src/main/java/com/farmer/backend/api/service/search/SearchService.java
  src/main/java/com/farmer/backend/domain/product/Product.java
  src/main/java/com/farmer/backend/domain/search/SearchQueryRepositoryImpl.java
Labels: bug

#265 Feat/user/search : 검색 상품 정렬 기능 수정
  src/main/java/com/farmer/backend/api/service/search/SearchService.java
Labels: bug

#266 Feat/user/search : 검색 상품 정렬 기능 수정
  src/main/java/com/farmer/backend/api/service/search/SearchService.java
Labels: bug

#267 Feature/member/orders: 주문/결제 완료시 결제 도메인 데이터 저장 구현
  src/main/java/com/farmer/backend/api/controller/order/OrderController.java
  src/main/java/com/farmer/backend/api/controller/order/response/ResponseOrderCompleteDto.java
  src/main/java/com/farmer/backend/api/service/order/OrderService.java
  src/main/java/com/farmer/backend/domain/orders/OrderQueryRepository.java
  src/main/java/com/farmer/backend/domain/orders/OrderRepository.java
  src/main/java/com/farmer/backend/domain/payment/Payment.java
Labels: feature, performance

#269 Feature/member/orders: 주문/결제 완료시 결제 도메인 데이터 저장 구현
  src/main/java/com/farmer/backend/api/controller/order/OrderController.java
  src/main/java/com/farmer/backend/api/controller/order/response/ResponseOrderCompleteDto.java
  src/main/java/com/farmer/backend/api/service/order/OrderService.java
  src/main/java/com/farmer/backend/domain/orders/OrderQueryRepository.java
  src/main/java/com/farmer/backend/domain/orders/OrderRepository.java
  src/main/java/com/farmer/backend/domain/payment/Payment.java
Labels: feature, performance

#272 Feat/user/qna : qna controller test 오류 수정
  src/test/java/com/farmer/backend/api/controller/qna/QnAControllerTest.java
Labels: bug

#273 Test: 장바구니 상품 수량 변경 테스트 코드 수정
  src/test/java/com/farmer/backend/api/service/cart/CartServiceTest.java
Labels: bug, test

#274 Test: 장바구니 상품 수량 변경 테스트 코드 수정
  src/main/java/com/farmer/backend/api/controller/qna/QnAController.java
  src/main/java/com/farmer/backend/api/service/qna/ProductQnAService.java
  src/main/java/com/farmer/backend/domain/qna/ProductQnAQueryRepository.java
  src/main/java/com/farmer/backend/domain/qna/ProductQnAQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/domain/search/SearchQueryRepositoryImpl.java
  src/test/java/com/farmer/backend/api/controller/qna/QnAControllerTest.java
  src/test/java/com/farmer/backend/api/service/cart/CartServiceTest.java
  src/test/java/com/farmer/backend/api/service/qna/ProductQnAServiceTest.java
Labels: bug, test

#277 Feature/member/orders: 주문 조회 데이터 오류 수정
  src/main/java/com/farmer/backend/api/service/order/OrderService.java
  src/main/java/com/farmer/backend/domain/deliveryaddress/DeliveryAddress.java
  src/main/resources/application-jwt.yml
  src/test/java/com/farmer/backend/api/service/membersCoupon/MembersCouponServiceTest.java
Labels: bug, setting, test

#279 Feature/member/orders: 장바구니 삭제 로직 변경
  src/main/java/com/farmer/backend/api/controller/cart/CartController.java
  src/main/java/com/farmer/backend/api/service/cart/CartService.java
  src/main/resources/application-jwt.yml
  src/test/java/com/farmer/backend/api/service/cart/CartServiceTest.java
Labels: bug, test, refactor, performance

#280 Feature/member/orders: 장바구니 상품 삭제 로직 변경
  src/main/java/com/farmer/backend/api/controller/cart/CartController.java
  src/main/java/com/farmer/backend/api/service/cart/CartService.java
  src/main/resources/application-jwt.yml
  src/test/java/com/farmer/backend/api/service/cart/CartServiceTest.java
Labels: bug, test, refactor, performance

#282 Feature/member/orders: 장바구니 상품 추가 로직 변경
  src/main/java/com/farmer/backend/api/service/cart/CartService.java
  src/main/java/com/farmer/backend/domain/cart/CartQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/domain/cart/CartRepository.java
Labels: bug, feature

#283 Feature/member/orders: 장바구니 상품 추가 로직 변경
  src/main/java/com/farmer/backend/api/service/cart/CartService.java
  src/main/java/com/farmer/backend/domain/cart/CartQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/domain/cart/CartRepository.java
Labels: bug, feature

#289 Feature/user/member : 회원 도메인 [admin]
  src/main/java/com/farmer/backend/api/controller/AdminApiController.java
  src/main/java/com/farmer/backend/api/controller/member/MemberController.java
  src/main/java/com/farmer/backend/api/controller/member/request/SearchMemberCondition.java
  src/main/java/com/farmer/backend/api/controller/member/response/ResponseMemberInfoDto.java
  src/main/java/com/farmer/backend/api/controller/member/response/ResponseMemberListDto.java
  src/main/java/com/farmer/backend/api/service/member/MemberService.java
  src/main/java/com/farmer/backend/domain/member/MemberQueryRepository.java
  src/main/java/com/farmer/backend/domain/member/MemberQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/exception/ErrorCode.java
Labels: feature

#291 Feature/user/member : 토큰 재발급 응답값 변경
  src/main/java/com/farmer/backend/jwt/JwtAuthenticationProcessingFilter.java
  src/main/java/com/farmer/backend/jwt/JwtService.java
Labels: refactor

#290 Feature/user/member : 회원 도메인 [admin]
  src/main/java/com/farmer/backend/api/controller/AdminApiController.java
  src/main/java/com/farmer/backend/api/controller/member/MemberController.java
  src/main/java/com/farmer/backend/api/controller/member/request/SearchMemberCondition.java
  src/main/java/com/farmer/backend/api/controller/member/response/ResponseMemberInfoDto.java
  src/main/java/com/farmer/backend/api/controller/member/response/ResponseMemberListDto.java
  src/main/java/com/farmer/backend/api/service/member/MemberService.java
  src/main/java/com/farmer/backend/domain/member/MemberQueryRepository.java
  src/main/java/com/farmer/backend/domain/member/MemberQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/exception/ErrorCode.java
  src/main/java/com/farmer/backend/jwt/JwtAuthenticationProcessingFilter.java
  src/main/java/com/farmer/backend/jwt/JwtService.java
Labels: feature

#292 Feat/user/search : 검색 상품 응답값 변경
  src/main/java/com/farmer/backend/api/controller/search/SearchController.java
  src/main/java/com/farmer/backend/api/controller/search/response/ResponseSearchProductDto.java
  src/main/java/com/farmer/backend/domain/search/SearchQueryRepositoryImpl.java
Labels: refactor

#293 Feat/user/search : 검색 상품 응답값 변경
  src/main/java/com/farmer/backend/api/controller/search/SearchController.java
  src/main/java/com/farmer/backend/api/controller/search/response/ResponseSearchProductDto.java
  src/main/java/com/farmer/backend/domain/search/SearchQueryRepositoryImpl.java
Labels: refactor

#295 Feature/member/orders: 장바구니 합계금액에 옵션 금액을 합산하여 조회
  src/main/java/com/farmer/backend/api/controller/cart/response/ResponseCartProductListDto.java
  src/main/java/com/farmer/backend/api/controller/orderproduct/response/ResponseOrderProductDetailDto.java
  src/main/java/com/farmer/backend/domain/cart/CartQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/domain/orderproduct/OrderProductQueryRepositoryImpl.java
  src/test/java/com/farmer/backend/api/service/cart/CartServiceTest.java
Labels: refactor, performance

#296 Feature/member/orders: 장바구니 합계금액에 옵션 금액을 합산하여 조회
  src/main/java/com/farmer/backend/api/controller/cart/response/ResponseCartProductListDto.java
  src/main/java/com/farmer/backend/api/controller/orderproduct/response/ResponseOrderProductDetailDto.java
  src/main/java/com/farmer/backend/domain/cart/CartQueryRepositoryImpl.java
  src/main/java/com/farmer/backend/domain/orderproduct/OrderProductQueryRepositoryImpl.java
  src/test/java/com/farmer/backend/api/service/cart/CartServiceTest.java
Labels: refactor, performance
